In [117]:
# import libraries 

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [118]:
# loading csv file into pandas dataframe

# read ratings file
ratings = pd.read_csv('ratings2.csv')

# read properties data file
property_info = pd.read_csv('propertiesprocessed.csv')
property_info.set_index('property_id', inplace=True)

In [119]:
ratings.head()

userId  propertyId  rating
0       1           7       4
1       1          32       2
2       1          70       3
3       1          76       4
4       1         168       5

In [120]:
ratings.tail()

userId  propertyId  rating
775      80         555       4
776      80         908       4
777      80        1203       5
778      80        1258       4
779       1         867       3

In [121]:
ratings.shape

(780, 3)

In [122]:
ratings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 780 entries, 0 to 779
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   userId      780 non-null    int64
 1   propertyId  780 non-null    int64
 2   rating      780 non-null    int64
dtypes: int64(3)
memory usage: 18.4 KB


In [123]:
# DATA SPLITTING

from sklearn.model_selection import train_test_split

# Data Training Size = 70%
# Data Testing Size = 30%
X_train, X_test = train_test_split(ratings, test_size = 0.30, random_state = 42)

print(X_train.shape)
print(X_test.shape)

(546, 3)
(234, 3)


In [124]:
# pivot ratings into movie features
user_data = X_train.pivot(index = 'userId', columns = 'propertyId', values = 'rating').fillna(0)
user_data.head()

propertyId  2     3     4     5     6     7     8     10    11    13    ...  \
userId                                                                  ...   
1            0.0   0.0   0.0   0.0   0.0   4.0   0.0   0.0   0.0   0.0  ...   
2            0.0   0.0   0.0   0.0   0.0   0.0   3.0   0.0   0.0   0.0  ...   
3            0.0   0.0   0.0   0.0   0.0   0.0   0.0   3.0   0.0   0.0  ...   
4            0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   4.0   0.0  ...   
5            0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   3.0  ...   

propertyId  1584  1597  1604  1608  1610  1616  1674  1682  1687  1721  
userId                                                                  
1            0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2            0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3            0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4            0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
5            0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[5 rows x 377 columns]

In [125]:
# make a copy of train and test datasets
dummy_train = X_train.copy()
dummy_test = X_test.copy()

dummy_train['rating'] = dummy_train['rating'].apply(lambda x: 0 if x > 0 else 1)
dummy_test['rating'] = dummy_test['rating'].apply(lambda x: 1 if x > 0 else 0)

In [126]:
# The properties not rated by user is marked as 1 for prediction 
dummy_train = dummy_train.pivot(index = 'userId', columns = 'propertyId', values = 'rating').fillna(1)

# The properties not rated by user is marked as 0 for evaluation 
dummy_test = dummy_test.pivot(index ='userId', columns = 'propertyId', values = 'rating').fillna(0)

In [127]:
dummy_train.head()

propertyId  2     3     4     5     6     7     8     10    11    13    ...  \
userId                                                                  ...   
1            1.0   1.0   1.0   1.0   1.0   0.0   1.0   1.0   1.0   1.0  ...   
2            1.0   1.0   1.0   1.0   1.0   1.0   0.0   1.0   1.0   1.0  ...   
3            1.0   1.0   1.0   1.0   1.0   1.0   1.0   0.0   1.0   1.0  ...   
4            1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   0.0   1.0  ...   
5            1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   0.0  ...   

propertyId  1584  1597  1604  1608  1610  1616  1674  1682  1687  1721  
userId                                                                  
1            1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0  
2            1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0  
3            1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0  
4            1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0  
5            1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0  

[5 rows x 377 columns]

In [128]:
dummy_test.head()

propertyId  6     10    16    17    19    36    41    44    45    52    ...  \
userId                                                                  ...   
1            0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
2            0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0  ...   
3            0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
4            0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0  ...   
5            0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   

propertyId  1597  1617  1619  1639  1693  1704  1721  1732  1784  1805  
userId                                                                  
1            0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2            0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3            0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4            0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
5            0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[5 rows x 200 columns]

In [129]:
#ITEM BASED COLLABORATIVE FILTERING

In [130]:
#set property features
property_features = X_train.pivot(index = 'propertyId', columns = 'userId', values = 'rating').fillna(0)
property_features.head()

userId       1    2    3    4    5    6    7    8    9    10  ...   71   72  \
propertyId                                                    ...             
2           0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
3           0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
4           0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
5           0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
6           0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   

userId       73   74   75   76   77   78   79   80  
propertyId                                          
2           0.0  0.0  0.0  0.0  0.0  3.0  0.0  0.0  
3           0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
4           0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
5           0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
6           0.0  0.0  0.0  0.0  0.0  0.0  4.0  0.0  

[5 rows x 79 columns]

In [131]:
from sklearn.metrics.pairwise import cosine_similarity

# Item Similarity Matrix using Cosine similarity as a similarity measure between Items
item_similarity = cosine_similarity(property_features)
item_similarity[np.isnan(item_similarity)] = 0
print(item_similarity)
print("- "*10)
print(item_similarity.shape)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
- - - - - - - - - - 
(377, 377)


In [132]:
#Predicting User Ratings

item_predicted_ratings = np.dot(property_features.T, item_similarity)
item_predicted_ratings

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 1.19522861,
        2.20863052],
       ...,
       [7.94336813, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.74077656],
       [0.        , 0.        , 1.69705627, ..., 0.        , 0.        ,
        0.        ]])

In [133]:
item_predicted_ratings.shape

(79, 377)

In [134]:
dummy_train.shape

(79, 377)

In [135]:
#Filtering the ratings only for the properties not already rated by the user for recommendation

# np.multiply for cell-by-cell multiplication 

item_final_ratings = np.multiply(item_predicted_ratings, dummy_train)
item_final_ratings.head()

propertyId  2     3     4         5     6         7     8     10        11    \
userId                                                                         
1            0.0   0.0   0.0  0.000000   0.0  0.000000   0.0   0.0  1.500000   
2            0.0   0.0   0.0  0.000000   0.0  0.000000   0.0   0.0  1.264911   
3            0.0   0.0   0.0  0.000000   0.0  0.000000   0.0   0.0  0.000000   
4            0.0   0.0   0.0  2.649065   0.0  0.000000   0.0   0.0  0.000000   
5            0.0   0.0   0.0  0.000000   0.0  1.107823   0.0   0.0  0.000000   

propertyId  13    ...  1584  1597  1604      1608  1610     1616  1674  1682  \
userId            ...                                                          
1            0.0  ...   0.0   0.0   0.0  1.024295   0.0  2.12132   0.0   0.0   
2            0.0  ...   0.0   0.0   0.0  0.000000   0.0  0.00000   0.0   0.0   
3            0.0  ...   0.0   0.0   0.0  0.000000   0.0  0.00000   0.0   0.0   
4            0.0  ...   0.0   0.0   0.0  0.000000   0.0  0.00000   0.0   0.0   
5            0.0  ...   0.0   0.0   0.0  0.000000   0.0  0.00000   0.0   0.0   

propertyId      1687      1721  
userId                          
1           0.000000  0.000000  
2           0.000000  0.000000  
3           1.195229  2.208631  
4           0.000000  0.000000  
5           0.000000  0.000000  

[5 rows x 377 columns]

In [149]:
#EXAMPLE OUTPUT

# Function to get property info based on property_id
def get_property_info(property_id):
    return property_info.loc[property_id]

# Modify the recommendation output code
top_properties = item_final_ratings.iloc[79].sort_values(ascending=False)[0:5]

unrated_properties = user_data.loc[79][user_data.loc[79] == 0].index
# Filter top rated properties to include only unrated ones
top_unrated_properties = top_properties[top_properties.index.isin(unrated_properties)].head(5)

# Display property name along with propertyId
for property_id, rating in top_unrated_properties.items():
    property_name = get_property_info(property_id)['prop_name']
    print(f"Property ID: {property_id}, Property Name: {property_name}, Rating: {rating}")
    print("\n")


IndexError: single positional indexer is out-of-bounds

In [137]:
#EVALUATION

test_item_features = X_test.pivot(index = 'propertyId', columns = 'userId', values = 'rating').fillna(0)
test_item_similarity = cosine_similarity(test_item_features)
test_item_similarity[np.isnan(test_item_similarity)] = 0 

print(test_item_similarity)
print("- "*10)
print(test_item_similarity.shape)

[[1.         0.43314808 0.         ... 0.         0.         0.        ]
 [0.43314808 1.         0.         ... 0.         0.         0.        ]
 [0.         0.         1.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 1.         0.         0.        ]
 [0.         0.         0.         ... 0.         1.         0.        ]
 [0.         0.         0.         ... 0.         0.         1.        ]]
- - - - - - - - - - 
(200, 200)


In [138]:
item_predicted_ratings_test = np.dot(test_item_features.T, test_item_similarity )
item_predicted_ratings_test

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [139]:
test_item_final_rating = np.multiply(item_predicted_ratings_test, dummy_test)
test_item_final_rating.head()

propertyId  6     10    16    17    19    36    41    44    45    52    ...  \
userId                                                                  ...   
1            0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
2            0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   3.0   0.0  ...   
3            0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
4            0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  17.0  ...   
5            0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   

propertyId  1597  1617  1619  1639  1693  1704  1721  1732  1784  1805  
userId                                                                  
1            0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2            0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3            0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4            0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
5            0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[5 rows x 200 columns]

In [140]:
ratings['rating'].describe()

count    780.000000
mean       3.682051
std        0.975403
min        1.000000
25%        3.000000
50%        4.000000
75%        4.000000
max        5.000000
Name: rating, dtype: float64

In [141]:
from sklearn.preprocessing import MinMaxScaler

X = test_item_final_rating.copy() 
X = X[X > 0] # only consider non-zero values as 0 means the user haven't rated the movies

scaler = MinMaxScaler(feature_range = (0.5, 5))
scaler.fit(X)
pred = scaler.transform(X)

print(pred)

[[nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 ...
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]]


In [142]:
# total non-NaN value
total_non_nan = np.count_nonzero(~np.isnan(pred))
total_non_nan

234

In [143]:
test = X_test.pivot(index = 'userId', columns = 'propertyId', values = 'rating')
test.head()

propertyId  6     10    16    17    19    36    41    44    45    52    ...  \
userId                                                                  ...   
1            NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...   
2            NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   3.0   NaN  ...   
3            NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...   
4            NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   3.0  ...   
5            NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...   

propertyId  1597  1617  1619  1639  1693  1704  1721  1732  1784  1805  
userId                                                                  
1            NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
2            NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
3            NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
4            NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
5            NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  

[5 rows x 200 columns]

In [144]:
# RMSE Score

diff_sqr_matrix = (test - pred)**2
sum_of_squares_err = diff_sqr_matrix.sum().sum() # df.sum().sum() by default ignores null values

rmse = np.sqrt(sum_of_squares_err/total_non_nan)
print(rmse)

3.0310090517344555


In [145]:
# Mean abslute error

mae = np.abs(pred - test).sum().sum()/total_non_nan
print(mae)

2.779672028401996


In [146]:
from sklearn.metrics import precision_score, recall_score, f1_score

# Convert predictions to binary values (1 if predicted rating > threshold, 0 otherwise)
threshold = 3.5  # You can adjust this threshold based on your rating scale
binary_predictions = (pred > threshold).astype(int)

# Flatten the true and predicted ratings matrices
flat_test = test.values.flatten()
flat_predictions = binary_predictions.flatten()

# Remove NaN values
nan_indices = np.isnan(flat_test)
flat_test = flat_test[~nan_indices]
flat_predictions = flat_predictions[~nan_indices]

# Calculate precision, recall, and F1 score with micro average
precision = precision_score(flat_test, flat_predictions, average='micro')
recall = recall_score(flat_test, flat_predictions, average='micro')
f1 = f1_score(flat_test, flat_predictions, average='micro')

print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)


Precision: 0.0
Recall: 0.0
F1 Score: 0.0
